# Generated by Django 4.2.11 on 2024-04-16 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shopitem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "images",
                    models.ImageField(upload_to=shopitem.models.item_image_path),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("payment_method", models.CharField(max_length=100)),
                ("pickup_method", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("condition", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
