# Generated by Django 4.2.11 on 2024-04-17 07:40

from django.db import migrations, models
import shopitem.models


class Migration(migrations.Migration):

    dependencies = [
        ("shopitem", "0002_rename_shopitem_secondhanditem_swapitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=shopitem.models.item_image_path)),
            ],
        ),
        migrations.RemoveField(
            model_name="secondhanditem",
            name="images",
        ),
        migrations.RemoveField(
            model_name="swapitem",
            name="images",
        ),
        migrations.AddField(
            model_name="secondhanditem",
            name="images",
            field=models.ManyToManyField(
                related_name="second_hand_items", to="shopitem.itemimage"
            ),
        ),
        migrations.AddField(
            model_name="swapitem",
            name="images",
            field=models.ManyToManyField(
                related_name="swap_items", to="shopitem.itemimage"
            ),
        ),
    ]
