# Generated by Django 4.2.11 on 2024-04-17 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shopitem", "0006_secondhanditem_contacts_secondhanditem_isforswap_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondhanditem",
            name="pickup_method",
        ),
        migrations.AddField(
            model_name="secondhanditem",
            name="published",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="secondhanditem",
            name="contacts",
            field=models.CharField(max_length=100),
        ),
    ]
