# Generated by Django 4.2.11 on 2024-04-17 16:43

from django.db import migrations, models
import django.utils.timezone
import shopitem.models


class Migration(migrations.Migration):

    dependencies = [
        ("shopitem", "0007_remove_secondhanditem_pickup_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secondhanditem",
            old_name="images",
            new_name="images1",
        ),
        migrations.AddField(
            model_name="secondhanditem",
            name="images2",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to=shopitem.models.item_image_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondhanditem",
            name="images3",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to=shopitem.models.item_image_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondhanditem",
            name="images4",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to=shopitem.models.item_image_path,
            ),
            preserve_default=False,
        ),
    ]
